### PR TITLE
[merged] Add a commctl.cli module

### PR DESCRIPTION
**Pull request by mbarnes**
I hope I added sufficient exposition for some of the odd-looking changes I had to make to be compatible with `atomic`.

Note, the classes I copied over from `client_script.py` (`Client`, `MultiServerSession`, etc.) are unchanged.  The weirdness is all in `Dispatcher` and `add_subparsers()`.

I'm not yet done with my `atomic` branch, but the core change is very small:
https://github.com/mbarnes/atomic/commit/3e927eb539d3e1c77acef7057076ed60f688f436

### CODE REVIEW

**Comment by ashcrow** [comment]
Looks like travis timed out for some reason...

**Comment by ashcrow** [comment]
- flake8: https://travis-ci.org/projectatomic/commctl/builds/124010322#L363-L367
- test error: https://travis-ci.org/projectatomic/commctl/builds/124010322#L388

I think the test error is possibly a missing mock so it's attempting to make a call to a server and timing out.

**Comment by ashcrow** [comment]
Changes are looking good so far (with exception to the two errors above).

**Comment by mbarnes** [comment]
Yeah sorry, I pushed this a little prematurely.  Everything worked under `virtualenv`.

I think the tests are somehow triggering the interactive prompts and it's timing out on that.

**Comment by mbarnes** [comment]
Tests aren't mock-blocked anymore, but now I'm fighting with the YAML dumper.

`yaml.dump()` seems to be ignoring `explicit_end=False`, or else there's some other option that's causing the end-of-document marker `...` which is breaking the `create passhash` tests and also just looks ugly to users.  What documentation I've found so far, frankly, sucks.  :rage:

**Comment by ashcrow** [comment]
@mbarnes interesting. I can't seem to reproduce that issue with direct usage:

``` python
In [8]: yaml.dump({'test': 'ok'}, explicit_end=False, default_flow_style=False, Dumper=yaml.SafeDumper)
Out[8]: 'test: ok\n'
```

~~Are you getting the same issue running unittests locally?~~ I can reproduce the test failures when running locally with your branch. Looking into it too.

**Comment by mbarnes** [comment]
:arrow_up: I hope you have a better idea than this, but the tests pass now.

I think the marker is only printed for ~~lists and~~ literals?  Not for dictionaries, from what I've seen.

**Ed:** just literals

**Comment by ashcrow** [comment]
@mbarnes ah ha, yeah. It looks like literals add `...`.

``` python
In [2]: yaml.dump(['test'], explicit_end=False, default_flow_style=False, Dumper=yaml.SafeDumper)Out[2]: '- test\n'

In [3]: yaml.dump('test', explicit_end=False, default_flow_style=False, Dumper=yaml.SafeDumper)
Out[3]: 'test\n...\n'
```

The weird thing is that if you use the current HEAD it passes fine. Did you change types per chance?

**Comment by mbarnes** [comment]
> The weird thing is that if you use the current HEAD it passes fine. Did you change types per chance?

Not intentionally.  Confirmed HEAD passes for me too.

**Comment by ashcrow** [comment]
@mbarnes if the types didn't change my first thought would be to always force iterable instances to output:

``` python
...
            call_result = bound_method(**self._args.__dict__)
            if not getattr(call_result, '__iter__', None):
                call_result = [call_result]
            output_data = yaml.dump(
...
```

OR not dumping literals...

``` python
...
            call_result = bound_method(**self._args.__dict__)
            if getattr(call_result, '__iter__', None):
                output_data = yaml.dump(
                ...
            else:
                print(call_result)
...
```

**Comment by ashcrow** [comment]
I don't think you did change types. It looks the same to me.

``` diff
+        return bcrypt.hashpw(pw, bcrypt.gensalt(log_rounds=kwargs['rounds']))
-        return bcrypt.hashpw(pw, bcrypt.gensalt(log_rounds=kwargs['rounds']))
```

**Comment by ashcrow** [comment]
This seems to work.

``` diff
index 8427cda..9f07890 100644
--- a/src/commctl/cli.py
+++ b/src/commctl/cli.py
@@ -449,12 +449,13 @@ class Dispatcher(object):
                 self._args.main_command, self._args.sub_command)
             bound_method = getattr(client, method_name)
             call_result = bound_method(**self._args.__dict__)
-            output_data = yaml.dump(
-                call_result,
-                default_flow_style=False,
-                Dumper=yaml.SafeDumper,
-                explicit_end=False)
-            print(output_data.strip())
+            if getattr(call_result, '__iter__', None):
+                call_result = yaml.dump(
+                    call_result,
+                    default_flow_style=False,
+                    Dumper=yaml.SafeDumper,
+                    explicit_end=False)
+            print(str(call_result).strip())
```

**Comment by mbarnes** [comment]
:arrow_up: I like your 2nd suggestion.  Less hacky fix.

**Comment by ashcrow** [comment]
Looks good! :smile: 

Let me know when it's ready to go.

**Comment by mbarnes** [comment]
Check if my `setup.py` change looks right for what I'm trying to do.  I kinda just tried things until `flake8` was happy.

**Comment by ashcrow** [comment]
Technically it should be `commctl/cli` though it does confused `flake8`. Is there a specific need to explicitly call out that module in `py_modules`?

With `py_modules` commented out the module is still installed:

``` bash
$ ./setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/commctl
copying src/commctl/cli.py -> build/lib/commctl
copying src/commctl/__init__.py -> build/lib/commctl
copying src/commctl/client_script.py -> build/lib/commctl
(tbdenv)[steve@bitfall commctl]$ ls build/lib/commctl/
client_script.py  cli.py            __init__.py       
```

**Comment by mbarnes** [comment]
Maybe there isn't - it's not entirely clear to me how `virtualenv` or eggs work.

I thought I needed a `.../site-packages/commctl` directory like I see for other packages, and assumed `py_modules` would get me that.  But I seem to be importing from the egg file anyway, so maybe I don't need `py_modules`?

Very confused...

**Comment by ashcrow** [comment]
I don't think you need it as we are using these two lines which should find all items:

``` python
    package_dir={'': 'src'},
    packages=find_packages('src'),
```

If we didn't do that we'd need to list out packages and/or modules.

**Comment by mbarnes** [comment]
:arrow_up: I removed it.

**Comment by ashcrow** [comment]
LGTM

@cgwalters-bot try

**Comment by ashcrow** [comment]
@cgwalters-bot r+

**Pull request closed without merging**
