### PR TITLE
[merged] Make command syntax more palatable to atomic

### PR DESCRIPTION
**Pull request by mbarnes**
Second pass at this.

`add_subparsers()` now takes keyword arguments to override base command names, the driving use case being `host='rhost'` for atomic.  I didn't want `commctl rhost`.

Additionally, this inverts the command syntax.  The commands are now:

```
    commctl cluster create
    commctl cluster delete
    commctl cluster get
    commctl cluster list
    commctl cluster restart start
    commctl cluster restart status
    commctl cluster upgrade start
    commctl cluster upgrade status
    commctl host create
    commctl host delete
    commctl host get
    commctl host list
    commctl passhash
```

Note what I did for `restart` and `upgrade`.  My reasoning there is by principle of least surprise I don't want `atomic upgrade` to be a thing.  I've mistyped that too many times when I meant `atomic host upgrade` and I think it would be misleading.

Also, `passhash` is an oddball case.  I debated whether to even add that to atomic.

### CODE REVIEW

**Comment by ashcrow** [comment]
At first pass I think this makes sense. Before we commit to it for `commctl` lets get @rhatdan's take on it as well.

**Comment by mbarnes** [comment]
> At first pass I think this makes sense. Before we commit to it for commctl lets get @rhatdan's take on it as well.

@rhatdan responded over on https://github.com/projectatomic/atomic/pull/354

I made the `passhash` command exclusive to `commctl`.  This is ready for review now.

**Comment by ashcrow** [comment]
Will review shortly.

**Comment by mbarnes** [comment]
Actually hold off a bit longer.  I think I need to make further adjustments for `atomic` compatibility.  Should have tested both before pushing... my bad.  :disappointed:

**Comment by ashcrow** [comment]
No problem. Let me know when to review.

**Comment by mbarnes** [comment]
Sorry for the confusion.  I had to rebase or the diffs wouldn't have made any sense.  I reworked the `commctl.cli` API since we've now partitioned this into two top-level `atomic` commands, but otherwise it's similar to before.

**Comment by ashcrow** [comment]
I just went back over it and it looks good!

@rh-atomic-bot try

**Comment by ashcrow** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
